
const RestaurantViewActionsConstants = {

  RESTAURANT_VIEW_MINIFY: "RESTAURANT_VIEW_MINIFY",
  RESTAURANT_VIEW_SHOW_REVIEW: "RESTAURANT_VIEW_SHOW_REVIEW",  
  
  RESTAURANT_VIEW_CHANGE_TOPIC: "RESTAURANT_VIEW_CHANGE_TOPIC",
  RESTAURANT_VIEW_CHANGE_RATING: "RESTAURANT_VIEW_CHANGE_RATING",

  RESTAURANT_VIEW_CHANGE_SORTING: "RESTAURANT_VIEW_CHANGE_SORTING",
  RESTAURANT_VIEW_CHANGE_TIME_SORTING: "RESTAURANT_VIEW_CHANGE_TIME_SORTING",
  RESTAURANT_VIEW_HIDE_REVIEW: "RESTAURANT_VIEW_HIDE_REVIEW",
  RESTAURANT_VIEW_CHANGE_D_FILTER: "RESTAURANT_VIEW_CHANGE_D_FILTER",  
  
  RESTAURANT_VIEW_UNMINIFY: "RESTAURANT_VIEW_UNMINIFY"
};

export { RestaurantViewActionsConstants };
