const SearchActionsConstants = {
  // LOAD SEARCH RESULTS
  SEARCH_LOAD_SEARCH: "SEARCH_LOAD_SEARCH",
  SEARCH_CHANGE_SEARCH_TOPIC: "SEARCH_CHANGE_SEARCH_TOPIC",
  SEARCH_CHANGE_RATING: "SEARCH_CHANGE_RATING",
  SEARCH_LOAD_SEARCH_SUCCESS: "SEARCH_LOAD_SEARCH_SUCCESS",
  SEARCH_CHANGE_SORTING: "SEARCH_CHANGE_SORTING",
  SEARCH_CHANGE_SEARCH_KEY: "SEARCH_CHANGE_SEARCH_KEY",
  // CHANGE SELECTION KEY
  SEARCH_CHANGE_SELECTION: "SEARCH_CHANGE_SELECTION",
  SEARCH_CHANGE_LOCATION: "SEARCH_CHANGE_LOCATION",
  SEARCH_CHANGE_D_FILTER: "SEARCH_CHANGE_D_FILTER",

  SEARCH_LOAD_SEARCH_FAILED: "SEARCH_LOAD_SEARCH_FAILED",
  SEARCH_CHANGE_SCALE: "SEARCH_CHANGE_SCALE"
};

export { SearchActionsConstants };
