const LoginConstants = {
  LOGIN: "LOGIN",  
  LOGIN_SUCCESS: "LOGIN_SUCCESS",  
  LOGIN_FAILED: "LOGIN_FAILED",  
  LOGIN_CHANGE_USER: "LOGIN_CHANGE_USER",
  LOGOUT: "LOGOUT",
  LOGOUT_FAILED: "LOGOUT_FAILED",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS"
};

export { LoginConstants };
