const UserProfileFormConstants = {
  EDIT_USER: "EDIT_USER",
  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAILED: "EDIT_USER_FAILED",  
  EDIT_USER_USER_VALIDATION: "EDIT_USER_USER_VALIDATION",
  EDIT_USER_USER_VALIDATION_FAILED: "EDIT_USER_USER_VALIDATION_FAILED",  
  EDIT_USER_USER_VALIDATION_SUCCESS: "EDIT_USER_USER_VALIDATION_SUCCESS",
  EDIT_USER_CHANGE_USER: "EDIT_USER_CHANGE_USER",
  EDIT_USER_CHANGE_PICTURE: "EDIT_USER_CHANGE_PICTURE",  
  EDIT_USER_CHANGE_LOCATION: "EDIT_USER_CHANGE_LOCATION",
  EDIT_USER_LOAD_USER_DATA: "EDIT_USER_LOAD_USER_DATA",
  EDIT_USER_LOAD_USER_DATA_SUCCESS: "EDIT_USER_LOAD_USER_DATA_SUCCESS",
  EDIT_USER_LOAD_USER_DATA_FAILED: "EDIT_USER_LOAD_USER_DATA_FAILED"
};

export { UserProfileFormConstants };
