
const AddRestaurantFormConstants = {
  ADD_NEW_RESTAURANT: "ADD_NEW_RESTAURANT",
  ADD_NEW_RESTAURANT_SUCC: "ADD_NEW_RESTAURANT_SUCC",
  ADD_NEW_RESTAURANT_FAIL: "ADD_NEW_RESTAURANT_FAIL",
  RESTAURANT_CHANGE_NAME: "RESTAURANT_CHANGE_NAME",
  RESTAURANT_CHANGE_LOCATION: "RESTAURANT_CHANGE_LOCATION"
};

export { AddRestaurantFormConstants };
