const ReviewEditActionsConstants = {
  REVIEW_EDIT: "REVIEW_EDIT",
  REVIEW_EDIT_DEL_FAILED: "REVIEW_EDIT_DEL_FAILED",
  REVIEW_EDIT_FAILED: "REVIEW_EDIT_FAILED",
  REVIEW_EDIT_DEL_SUCCESS: "REVIEW_EDIT_DEL_SUCCESS",
  REVIEW_EDIT_CHANGE_RATING: "REVIEW_EDIT_CHANGE_RATING",
  REVIEW_EDIT_LOAD_REVIEW_FAILED: "REVIEW_EDIT_LOAD_REVIEW_FAILED",
  REVIEW_EDIT_UNMINIFY: "REVIEW_EDIT_UNMINIFY",
  REVIEW_EDIT_MINIFY: "REVIEW_EDIT_MINIFY",

  REVIEW_EDIT_SET_PICTURE: "REVIEW_EDIT_SET_PICTURE",
  REVIEW_EDIT_ADD_PICTURE: "REVIEW_EDIT_ADD_PICTURE",

  REVIEW_EDIT_LOAD: "REVIEW_EDIT_LOAD",
  REVIEW_EDIT_LOAD_REVIEW_SUCC: "REVIEW_EDIT_LOAD_REVIEW_SUCC",
  REVIEW_EDIT_SUCCESS: "REVIEW_EDIT_SUCCESS",

  REVIEW_EDIT_DEL_REVIEW: "REVIEW_EDIT_DEL_REVIEW"
};

export { ReviewEditActionsConstants };


