
const RestaurantReviewActionsConstants = {
  REVIEW: "REVIEW",
  REVIEW_ADD_PICTURE: "REVIEW_ADD_PICTURE",
  REVIEW_FAILED: "REVIEW_FAILED",
  REVIEW_SUCCESS: "REVIEW_SUCCESS",
  REVIEW_SET_PICTURE: "REVIEW_SET_PICTURE",
  REVIEW_CHANGE_RATING: "REVIEW_CHANGE_RATING"
  
};

export { RestaurantReviewActionsConstants };
