
const RegisterConstants =
{
  REGISTER: "REGISTER",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILED: "REGISTER_FAILED",
  REGISTER_USER_VALIDATION: "REGISTER_USER_VALIDATION",
  REGISTER_USER_VALIDATION_SUCCESS: "REGISTER_USER_VALIDATION_SUCCESS",
  REGISTER_USER_VALIDATION_FAILED: "REGISTER_USER_VALIDATION_FAILED",
  REGISTER_CHANGE_USER: "REGISTER_CHANGE_USER",
  REGISTER_CHANGE_LOCATION: "REGISTER_CHANGE_LOCATION",
  REGISTER_CHANGE_PICTURE: "REGISTER_CHANGE_PICTURE"
};

export { RegisterConstants };
