
const ReviewViewActionsConstants = {
  REVIEW_VIEW_LOAD_VIEW_SUCCESS: "REVIEW_VIEW_LOAD_VIEW_SUCCESS",  
  REVIEW_VIEW_MINIFY_VIEW: "REVIEW_VIEW_MINIFY_VIEW",
  REVIEW_VIEW_CHANGE_KEY: "REVIEW_VIEW_CHANGE_KEY",

  REVIEW_VIEW_CHANGE_SELECTION: "REVIEW_VIEW_CHANGE_SELECTION",
  REVIEW_VIEW_UNMINIFY_VIEW: "REVIEW_VIEW_UNMINIFY_VIEW",    
  // LOAD_VIEW
  REVIEW_VIEW_LOAD: "REVIEW_VIEW_LOAD",

  REVIEW_VIEW_LOAD_VIEW_FAILED: "REVIEW_VIEW_LOAD_VIEW_FAILED"

};

export { ReviewViewActionsConstants };
